version: '3.9'

services:
  db:
    container_name: hackku-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - hackku-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 10s
  backend:
    container_name: hackku-backend
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - backend.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 10s
  frontend:
    container_name: hackku-frontend
    build:
      context: ./frontend
      args:
        - VITE_BACKEND_URL=http://localhost:8000
    ports:
      - "8080:8080"
    depends_on:
      backend:
        condition: service_healthy

volumes:
  hackku-data: